[package]
name = "struct_indexer_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.105"
quote = "1.0.21"
struct_indexer_core = { path = "../core" }

[lib]
proc-macro = true
