[package]
name = "struct_indexer_dedicated_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
struct_indexer_core = { path = "../core" }
struct_indexer_macro = { path = "../macro" }
